-- ============================================================
-- AroMe — Données de test
-- 20 articles · 20 bourses · 20 opportunités · 20 événements
-- Compatible avec le schéma exact fourni
-- ============================================================

-- ── Nettoyage (préserve auth.users et profiles) ──────────────
TRUNCATE TABLE public.saves                RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.applications         RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.event_registrations  RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.contact_messages     RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.events               RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.opportunities        RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.scholarships         RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.articles             RESTART IDENTITY CASCADE;

-- ============================================================
-- ARTICLES (20)
-- ============================================================
INSERT INTO public.articles
  (slug, title, excerpt, content, category, author_name, reading_time, featured,
   published, published_at, image_gradient, tags, views, saves_count)
VALUES

('sommet-ua-addis-abeba-2025',
 'Le Sommet de l''Union Africaine redéfinit l''agenda continental pour 2025',
 'Les chefs d''État africains réunis à Addis-Abeba ont adopté une feuille de route ambitieuse axée sur la souveraineté alimentaire, la transition énergétique et l''intégration monétaire.',
 '{"intro":"Le 38ème Sommet de l''Union Africaine s''est tenu les 15 et 16 février 2025 à Addis-Abeba, réunissant 54 chefs d''État et de gouvernement autour de thématiques cruciales pour l''avenir du continent.","blocks":[{"type":"heading","level":2,"text":"Une feuille de route en trois axes"},{"type":"paragraph","text":"Les délégués ont adopté à l''unanimité la Déclaration d''Addis-Abeba, un document de 47 pages fixant les priorités continentales jusqu''en 2030. Le premier axe concerne la souveraineté alimentaire."},{"type":"pullquote","text":"L''Afrique ne peut plus se permettre de nourrir le monde tout en important sa propre nourriture.","author":"Moussa Faki Mahamat","role":"Président de la Commission de l''UA"},{"type":"factbox","title":"Chiffres clés du Sommet","facts":["54 pays représentés","47 milliards USD d''engagements","17 pays signataires du protocole monétaire","12 accords bilatéraux signés"]}]}',
 'Politique', 'Aminata Diallo', 8, true, true, '2025-02-17T08:00:00Z',
 'linear-gradient(135deg,#050010,#0a0020,#10003a)',
 ARRAY['UA','Addis-Abeba','Diplomatie','Intégration africaine'], 12450, 342),

('nigeria-tech-hub-lagos-milliard',
 'Lagos devient le premier hub tech africain à dépasser le milliard de dollars',
 'L''écosystème technologique nigérian franchit un cap historique avec des startups qui attirent des investisseurs du monde entier.',
 '{"intro":"Pour la première fois de son histoire, l''écosystème technologique de Lagos a agrégé plus d''un milliard de dollars de financements en une seule année civile.","blocks":[{"type":"heading","level":2,"text":"Un écosystème en pleine effervescence"},{"type":"paragraph","text":"Le rapport annuel Africa Tech Ecosystem révèle que Lagos concentre désormais 34% de tous les investissements tech du continent."},{"type":"factbox","title":"Top startups Lagos 2024","facts":["Flutterwave : 3Md$ de valorisation","Paystack : opérationnel dans 6 pays","Interswitch : IPO prévue T3 2025","Kuda Bank : 1,4M de clients actifs"]},{"type":"alert","variant":"tip","message":"Les investisseurs étrangers bénéficient d''un régime fiscal favorable avec la nouvelle loi sur les startups adoptée en 2024."}]}',
 'Tech', 'Chukwuemeka Obi', 7, true, true, '2025-02-14T10:30:00Z',
 'linear-gradient(135deg,#001a0f,#002e1a,#004025)',
 ARRAY['Nigeria','Tech','Startups','Fintech','Investissement'], 9870, 287),

('cop30-afrique-financement-climatique',
 'COP30 : l''Afrique exige 1 000 milliards pour sa transition climatique',
 'La coalition africaine présente un front uni pour obtenir des financements climatiques à la hauteur des défis du continent.',
 '{"intro":"La délégation africaine à la COP30 a présenté une position commune sans précédent : 1 000 milliards de dollars annuels pour financer l''adaptation et la mitigation climatique.","blocks":[{"type":"heading","level":2,"text":"Une revendication historique et chiffrée"},{"type":"paragraph","text":"Pour la première fois, les 54 nations africaines parlent d''une seule voix avec un chiffre précis."},{"type":"pullquote","text":"Nous avons émis 4% des émissions mondiales depuis l''ère industrielle. Nous subissons 40% des impacts climatiques.","author":"Leila Benali","role":"Présidente COP28"},{"type":"steps","title":"Priorités climatiques africaines","items":[{"label":"Adaptation agricole","desc":"Semences résistantes, irrigation efficiente"},{"label":"Énergies renouvelables","desc":"Solaire, éolien pour 600 millions sans électricité"},{"label":"Financement des pertes","desc":"Compensation directe pour les pays touchés"}]}]}',
 'Environnement', 'Fatou Sow', 9, false, true, '2025-02-10T14:00:00Z',
 'linear-gradient(135deg,#001018,#001a28,#002535)',
 ARRAY['COP30','Climat','Afrique','Environnement','Financement'], 7230, 198),

('rwanda-sante-couverture-universelle',
 'Le Rwanda atteint 96% de couverture santé universelle : le modèle mondial',
 'Trente ans après le génocide, le Rwanda présente un système de santé parmi les plus performants d''Afrique subsaharienne.',
 '{"intro":"Le Rwanda a atteint un taux de couverture maladie universelle de 96%, faisant de ce pays un modèle étudié par l''OMS et reproduit par plus d''une dizaine de nations africaines.","blocks":[{"type":"heading","level":2,"text":"La Mutuelles de Santé : un génie pragmatique"},{"type":"paragraph","text":"La clé du succès rwandais réside dans les Mutuelles de Santé, un système d''assurance communautaire à cotisation modulée selon les revenus."},{"type":"factbox","title":"Indicateurs santé Rwanda 2024","facts":["Mortalité infantile : 32 pour 1000","Espérance de vie : 70,2 ans","96% couverture assurance maladie","Drones médicaux : 500 000 livraisons"]},{"type":"alert","variant":"info","message":"Le modèle rwandais a été adopté par le Kenya, l''Éthiopie et la Tanzanie."}]}',
 'Santé', 'Dr. Jean-Baptiste Bizimana', 6, false, true, '2025-02-08T09:00:00Z',
 'linear-gradient(135deg,#001005,#001a0a,#002814)',
 ARRAY['Rwanda','Santé','Couverture universelle'], 5640, 156),

('senegal-petrole-premiere-annee',
 'Sénégal : un an après le pétrole, les promesses face à la réalité',
 'Douze mois après le début de l''exploitation pétrolière, le Sénégal dresse un bilan nuancé.',
 '{"intro":"Un an après les premières extractions de pétrole du champ Sangomar, le Sénégal dresse un bilan contrasté entre revenus réels et projections initiales.","blocks":[{"type":"heading","level":2,"text":"Des recettes en deçà des projections"},{"type":"paragraph","text":"Les revenus pétroliers pour l''exercice 2024 s''élèvent à 890 milliards de FCFA, soit 15% en dessous des projections."},{"type":"pullquote","text":"Le pétrole doit financer la transformation structurelle de notre économie, pas simplement gonfler des statistiques.","author":"Bassirou Diomaye Faye","role":"Président du Sénégal"},{"type":"paragraph","text":"Le fonds souverain des générations futures est en cours de constitution avec 10% des revenus pétroliers."}]}',
 'Économie', 'Mariama Bâ', 7, true, true, '2025-02-05T11:00:00Z',
 'linear-gradient(135deg,#0a0800,#1a1400,#2a2000)',
 ARRAY['Sénégal','Pétrole','Économie','Ressources naturelles'], 8920, 234),

('can-2025-maroc-bilan',
 'CAN 2025 au Maroc : un tournoi record qui propulse le football africain',
 'La Coupe d''Afrique des Nations organisée au Maroc a battu tous les records d''affluence et d''audiences.',
 '{"intro":"La 35ème édition de la CAN s''est achevée sur une finale mémorable remportée par le Maroc devant 93 000 spectateurs.","blocks":[{"type":"heading","level":2,"text":"Des chiffres qui font l''histoire"},{"type":"paragraph","text":"2,4 millions de billets vendus, 1,8 milliard de téléspectateurs cumulés, 450 millions d''euros de retombées économiques."},{"type":"factbox","title":"Records CAN 2025","facts":["2,4 millions de spectateurs","93 000 : record finale","1,8 Md de téléspectateurs","127 buts en 52 matchs"]},{"type":"paragraph","text":"Au-delà du sport, le tournoi a renforcé un sentiment d''appartenance continentale."}]}',
 'Sport', 'Karim El Fassi', 5, true, true, '2025-02-01T20:00:00Z',
 'linear-gradient(135deg,#0e0005,#1a000a,#260010)',
 ARRAY['CAN 2025','Maroc','Football'], 18750, 521),

('ethiopie-startup-agritech-revolution',
 'Éthiopie : des startups agritech transforment 30 millions de paysans',
 'Une nouvelle génération d''entrepreneurs utilise l''IA et les drones pour révolutionner l''agriculture.',
 '{"intro":"Dans les Hauts Plateaux éthiopiens, des startups comme DigiFarm et AgriBora apportent des solutions numériques transformant des millions d''agriculteurs.","blocks":[{"type":"heading","level":2,"text":"L''IA au service du petit paysan"},{"type":"paragraph","text":"DigiFarm Ethiopia a développé une application de diagnostic des cultures qui fonctionne hors ligne en amharique. 2,3 millions d''agriculteurs l''utilisent."},{"type":"benefits","items":[{"icon":"🌾","label":"Rendement","value":"+28% en moyenne","highlight":true},{"icon":"💧","label":"Eau économisée","value":"35% de moins","highlight":false},{"icon":"💰","label":"Revenus paysans","value":"+40% annuel","highlight":true},{"icon":"📱","label":"Utilisateurs","value":"2,3 millions","highlight":false}]}]}',
 'Tech', 'Tigist Haile', 8, false, true, '2025-01-28T08:30:00Z',
 'linear-gradient(135deg,#001a0f,#002e1a,#004025)',
 ARRAY['Éthiopie','Agritech','Agriculture','Innovation'], 4350, 112),

('afrique-du-sud-elections-ramaphosa',
 'Afrique du Sud : Ramaphosa reconduit, le défi de l''unité nationale',
 'Après des élections marquées par la percée de nombreux partis, l''Afrique du Sud entre dans une ère de coalition.',
 '{"intro":"Le président Cyril Ramaphosa a été réélu dans le cadre d''un gouvernement d''unité nationale regroupant l''ANC et sept partis, une configuration sans précédent depuis 1994.","blocks":[{"type":"heading","level":2,"text":"Un paysage politique fragmenté"},{"type":"paragraph","text":"Pour la première fois depuis la fin de l''apartheid, l''ANC n''a pas obtenu la majorité absolue avec seulement 40% des suffrages."},{"type":"alert","variant":"warning","message":"Les agences de notation surveillent attentivement la stabilité du nouveau gouvernement."},{"type":"paragraph","text":"L''Afrique du Sud dispose d''institutions solides et d''une société civile active, meilleurs remparts contre les dérives autoritaires."}]}',
 'Politique', 'Thandiwe Mthembu', 7, false, true, '2025-01-25T15:00:00Z',
 'linear-gradient(135deg,#050010,#0a0020,#10003a)',
 ARRAY['Afrique du Sud','Politique','Élections'], 6780, 189),

('ghana-cacao-prix-record',
 'Ghana et Côte d''Ivoire obtiennent des prix records pour leur cacao',
 'Les deux géants mondiaux ont réussi à imposer un prix plancher de 4 000 dollars la tonne.',
 '{"intro":"L''alliance entre le Ghana et la Côte d''Ivoire, qui représentent 65% de l''offre mondiale, a porté ses fruits : un accord de prix plancher à 4 000 dollars la tonne.","blocks":[{"type":"heading","level":2,"text":"La prime de durabilité : un levier clé"},{"type":"paragraph","text":"La prime SCOPE a été revalorisée à 400 dollars la tonne, destinée à garantir un revenu décent aux 2,5 millions de planteurs."},{"type":"factbox","title":"Cacao en chiffres 2024","facts":["65% de l''offre mondiale","4 000$/tonne : prix plancher","2,5 millions de planteurs","Prime SCOPE : +400$/tonne"]},{"type":"paragraph","text":"L''ambition : porter à 25% la part du chocolat fabriqué en Afrique d''ici 2030."}]}',
 'Économie', 'Kwame Asante', 6, false, true, '2025-01-22T10:00:00Z',
 'linear-gradient(135deg,#0a0800,#1a1400,#2a2000)',
 ARRAY['Ghana','Côte d''Ivoire','Cacao','Commerce'], 5230, 143),

('kenya-intelligence-artificielle-gouvernement',
 'Le Kenya premier pays africain à intégrer l''IA dans son administration',
 'Nairobi déploie JaribuAI, un système qui automatise 200 services publics et réduit la corruption.',
 '{"intro":"Le Kenya a lancé JaribuAI, développé localement, qui automatise et optimise la délivrance de plus de 200 services publics.","blocks":[{"type":"heading","level":2,"text":"200 services, zéro corruption possible"},{"type":"paragraph","text":"JaribuAI élimine les intermédiaires dans les processus les plus sujets à la corruption."},{"type":"steps","title":"Comment fonctionne JaribuAI","items":[{"label":"Soumission numérique","desc":"Le citoyen soumet sa demande via l''application mobile"},{"label":"Vérification automatique","desc":"L''IA vérifie les documents et croise les bases de données"},{"label":"Décision et notification","desc":"Décision rendue sous 48h avec justification"},{"label":"Suivi et audit","desc":"Toutes les décisions archivées et auditables"}]},{"type":"paragraph","text":"L''UA envisage d''adapter le modèle kényan à d''autres pays membres."}]}',
 'Tech', 'Aisha Kamau', 9, true, true, '2025-01-20T09:00:00Z',
 'linear-gradient(135deg,#001a0f,#002e1a,#004025)',
 ARRAY['Kenya','Intelligence artificielle','Innovation'], 11200, 312),

('tunisie-culture-festival-carthage',
 'Festival de Carthage 2025 : la culture tunisienne rayonne à l''international',
 'La 60ème édition réaffirme le rôle de la Tunisie comme carrefour culturel méditerranéen.',
 '{"intro":"Le Festival International de Carthage célèbre son 60ème anniversaire avec 45 artistes de 23 pays sous les étoiles du théâtre antique.","blocks":[{"type":"heading","level":2,"text":"Un amphithéâtre, des siècles d''histoire"},{"type":"paragraph","text":"Le théâtre antique de Carthage, construit au IIème siècle et capable d''accueillir 5 000 spectateurs, offre un cadre incomparable."},{"type":"paragraph","text":"180 000 visiteurs attendus, 3 000 emplois créés, 45 millions de dinars de retombées économiques."}]}',
 'Culture', 'Sarra Belhadj', 5, false, true, '2025-01-18T16:00:00Z',
 'linear-gradient(135deg,#0a0500,#1a0e00,#2e1800)',
 ARRAY['Tunisie','Culture','Festival','Carthage'], 3210, 87),

('mali-or-exploitation-artisanale',
 'Mali : l''or artisanal, un secteur de 2 milliards qui défie l''État',
 'L''orpaillage artisanal génère des revenus colossaux mais échappe largement à la fiscalité.',
 '{"intro":"Le Mali est le 3ème producteur d''or africain. Un secteur artisanal informel de 2 milliards USD emploie 600 000 personnes dans les régions de Kayes et Sikasso.","blocks":[{"type":"heading","level":2,"text":"Un secteur qui fait vivre des centaines de milliers"},{"type":"paragraph","text":"Les orpailleurs artisanaux extraient entre 15 et 20 tonnes d''or par an, soit 20% de la production nationale."},{"type":"alert","variant":"warning","message":"L''OMS classe la contamination au mercure liée à l''orpaillage parmi les dix principales menaces sanitaires."},{"type":"paragraph","text":"Pure Earth a démontré que le remplacement du mercure par gravitation simple augmente les rendements de 15%."}]}',
 'Économie', 'Boubacar Coulibaly', 8, false, true, '2025-01-15T11:30:00Z',
 'linear-gradient(135deg,#0a0800,#1a1400,#2a2000)',
 ARRAY['Mali','Or','Mines','Économie'], 4120, 98),

('tanzanie-tourisme-kilimanjaro-record',
 'Tanzanie : le Kilimandjaro accueille un nombre record d''alpinistes',
 'La montagne la plus haute d''Afrique attire plus de 70 000 alpinistes par an.',
 '{"intro":"Le Kilimandjaro a accueilli 72 000 alpinistes en 2024, générant 380 millions de dollars de revenus touristiques mais menaçant l''écosystème.","blocks":[{"type":"heading","level":2,"text":"Une manne économique"},{"type":"paragraph","text":"L''industrie du Kilimandjaro fait vivre 15 000 personnes directement."},{"type":"factbox","title":"Kilimandjaro en chiffres","facts":["5 895 m : altitude","72 000 alpinistes en 2024","85% de taux de succès","82% de glaciers perdus depuis 1912"]},{"type":"paragraph","text":"Un système de quotas journaliers est envisagé dès 2026."}]}',
 'Environnement', 'Rose Mwangi', 6, false, true, '2025-01-12T08:00:00Z',
 'linear-gradient(135deg,#001018,#001a28,#002535)',
 ARRAY['Tanzanie','Kilimandjaro','Tourisme','Environnement'], 5670, 165),

('egypte-sante-mentale-tabou-brise',
 'Égypte : la santé mentale sort du tabou et devient enjeu de santé publique',
 'Une nouvelle génération brise les tabous culturels autour de la santé mentale.',
 '{"intro":"En Égypte, une révolution culturelle menée par des professionnels de santé et des influenceurs change radicalement le rapport à la santé mentale.","blocks":[{"type":"heading","level":2,"text":"Les réseaux sociaux, vecteurs de déstigmatisation"},{"type":"paragraph","text":"Des comptes gérés par des psychiatres égyptiens totalisent plus de 12 millions d''abonnés."},{"type":"paragraph","text":"L''OMS estime que 20% des Égyptiens souffrent de troubles mentaux, mais moins de 5% consultent."},{"type":"alert","variant":"tip","message":"Le ministère de la Santé a lancé un programme de formation de 5 000 médecins généralistes aux premiers soins en santé mentale."}]}',
 'Santé', 'Dr. Nada El-Rashidi', 7, false, true, '2025-01-10T13:00:00Z',
 'linear-gradient(135deg,#001005,#001a0a,#002814)',
 ARRAY['Égypte','Santé mentale','Société'], 6340, 178),

('mozambique-gaz-naturel-communautes',
 'Mozambique : les géants du gaz enrichissent-ils vraiment les communautés ?',
 'Le Mozambique fait face au défi de transformer ses ressources gazières en développement humain concret.',
 '{"intro":"Le Mozambique détient des réserves de gaz de 5 000 milliards de m3 dans le bassin de Rovuma. Mais les communautés locales voient-elles leur vie s''améliorer ?","blocks":[{"type":"heading","level":2,"text":"Une région riche de ressources, pauvre de développement"},{"type":"paragraph","text":"Cabo Delgado affiche les pires indicateurs de développement humain du Mozambique."},{"type":"pullquote","text":"Ils ont trouvé du gaz sur notre terre mais notre école n''a toujours pas de toit.","author":"Aldeia Hassan Ibrahim","role":"Leader communautaire"},{"type":"paragraph","text":"La loi prévoit 2,75% des revenus gaziers pour les communautés, mais les mécanismes de distribution restent opaques."}]}',
 'Économie', 'Ana Machava', 8, false, true, '2025-01-08T10:00:00Z',
 'linear-gradient(135deg,#0a0800,#1a1400,#2a2000)',
 ARRAY['Mozambique','Gaz naturel','Développement'], 3890, 94),

('algerie-eau-crisis-agriculture',
 'Algérie : la crise hydrique menace l''agriculture et accélère l''exode rural',
 'Face à une sécheresse persistante, l''Algérie doit repenser son modèle agricole.',
 '{"intro":"L''Algérie traverse sa pire crise hydrique depuis l''indépendance. Les barrages ne sont remplis qu''à 43% de leur capacité.","blocks":[{"type":"heading","level":2,"text":"Le paradoxe algérien de l''eau"},{"type":"paragraph","text":"L''Algérie possède d''immenses ressources en eau fossile dans le Sahara, mais cette eau n''est pas renouvelable."},{"type":"alert","variant":"warning","message":"Le GIEC prédit une diminution de 20 à 30% des précipitations en Algérie d''ici 2050."},{"type":"paragraph","text":"Solutions : 15 usines de dessalement en construction, réutilisation des eaux usées, irrigation goutte-à-goutte."}]}',
 'Environnement', 'Yanis Benali', 7, false, true, '2025-01-05T09:30:00Z',
 'linear-gradient(135deg,#001018,#001a28,#002535)',
 ARRAY['Algérie','Eau','Agriculture','Sécheresse'], 4560, 127),

('cote-divoire-cinema-nouveau-souffle',
 'Côte d''Ivoire : le cinéma abidjanais connaît un nouveau souffle',
 'Une nouvelle vague de cinéastes ivoiriens s''impose sur la scène internationale.',
 '{"intro":"Abidjan vibre au rythme d''une renaissance cinématographique avec cinq films sélectionnés dans des festivals internationaux en 2024.","blocks":[{"type":"heading","level":2,"text":"Des voix nouvelles pour des récits africains"},{"type":"paragraph","text":"La réalisatrice Awa Kouyaté, 29 ans, a fait sensation avec son premier long métrage sélectionné à Cannes."},{"type":"paragraph","text":"Le gouvernement ivoirien a créé le Fonds de Soutien au Cinéma Africain, doté de 5 milliards de FCFA annuels."}]}',
 'Culture', 'Adjoua Kouassi', 6, false, true, '2025-01-03T14:00:00Z',
 'linear-gradient(135deg,#0a0500,#1a0e00,#2e1800)',
 ARRAY['Côte d''Ivoire','Cinéma','Culture'], 2870, 76),

('zimbabwe-inflation-reconstruction',
 'Zimbabwe : dix ans après l''hyperinflation, une économie qui se reconstruit',
 'Malgré les séquelles d''une décennie catastrophique, le Zimbabwe présente des signes de stabilisation.',
 '{"intro":"Le Zimbabwe affiche une croissance de 5,3% et une inflation maîtrisée à 20%, quinze ans après la pire hyperinflation de l''histoire.","blocks":[{"type":"heading","level":2,"text":"Les réformes qui font bouger les lignes"},{"type":"paragraph","text":"L''introduction du ZiG (Zimbabwe Gold), adossé à l''or, a redonné confiance aux opérateurs économiques."},{"type":"paragraph","text":"Les exportations de tabac ont retrouvé 70% de leur niveau d''avant-crise."},{"type":"alert","variant":"info","message":"Le FMI conditionne ses financements à une plus grande transparence dans la gouvernance minière."}]}',
 'Économie', 'Tendai Moyo', 7, false, true, '2025-01-01T10:00:00Z',
 'linear-gradient(135deg,#0a0800,#1a1400,#2a2000)',
 ARRAY['Zimbabwe','Économie','Inflation','Reconstruction'], 3450, 89),

('cameroun-football-jeunes-talents',
 'Cameroun : l''usine à talents du football africain continue de produire',
 'Malgré un manque de structures, le Cameroun exporte des joueurs de classe mondiale.',
 '{"intro":"Le Cameroun reste une des nations les plus prolifiques avec 145 joueurs évoluant dans les championnats professionnels européens.","blocks":[{"type":"heading","level":2,"text":"Un talent naturel, un système défaillant"},{"type":"paragraph","text":"Paradoxe : le pays produit des joueurs de classe mondiale mais son championnat est l''un des moins organisés du continent."},{"type":"paragraph","text":"La diaspora finance des académies privées qui comblent le vide laissé par le secteur public."},{"type":"paragraph","text":"La FIFA et la CAF financent la rénovation de 12 académies régionales sur cinq ans."}]}',
 'Sport', 'Patrick Njoya', 5, false, true, '2024-12-28T17:00:00Z',
 'linear-gradient(135deg,#0e0005,#1a000a,#260010)',
 ARRAY['Cameroun','Football','Sport','Talents'], 7120, 203),

('afrique-intelligence-artificielle-risques',
 'L''IA en Afrique : entre opportunités immenses et risques de marginalisation',
 'Alors que l''IA transforme l''économie mondiale, l''Afrique doit choisir entre subir ou devenir acteur.',
 '{"intro":"La révolution de l''IA touche l''Afrique différemment. Certains pays saisissent l''opportunité, d''autres risquent d''être marginalisés.","blocks":[{"type":"heading","level":2,"text":"Les pionniers africains de l''IA"},{"type":"paragraph","text":"Zindi a formé 50 000 data scientists africains. InstaDeep a été acquise par BioNTech pour 362 millions d''euros."},{"type":"checklist","title":"Priorités pour une IA africaine souveraine","items":[{"label":"Formation massive","detail":"Intégrer l''IA dans les cursus de 54 pays"},{"label":"Données africaines","detail":"Bases de données en langues africaines"},{"label":"Infrastructure cloud locale","detail":"Réduire la dépendance aux datacenters étrangers"},{"label":"Cadre réglementaire","detail":"Lois protégeant les citoyens africains"}]},{"type":"paragraph","text":"L''UA a adopté une stratégie continentale avec 400 millions de dollars sur cinq ans."}]}',
 'Tech', 'Professeur Ama Owusu', 10, true, true, '2024-12-25T08:00:00Z',
 'linear-gradient(135deg,#001a0f,#002e1a,#004025)',
 ARRAY['Intelligence artificielle','Tech','Numérique','Innovation'], 9450, 278);

-- ============================================================
-- BOURSES (20)
-- ============================================================
INSERT INTO public.scholarships
  (slug, title, organization, country, flag, level, domain, deadline,
   urgent, amount, image_gradient, tags, published, views, saves_count, apply_url)
VALUES

('excellence-africa-oxford-2025',
 'Bourse Excellence Africa — Université d''Oxford',
 'Université d''Oxford', 'Royaume-Uni', '🇬🇧', 'Master', 'Toutes disciplines',
 '2025-04-15', false, '100% des frais + 18 000 £/an de bourse vie',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['Oxford','UK','Excellence','Master'], true, 3240, 187,
 'https://www.ox.ac.uk/admissions/graduate/fees-and-funding'),

('mastercard-foundation-scholars-2025',
 'Programme Mastercard Foundation Scholars 2025',
 'Mastercard Foundation', 'International', '🌍', 'Licence', 'Toutes disciplines',
 '2025-03-31', true, 'Intégrale : frais + logement + billets d''avion',
 'linear-gradient(135deg,#0a0800,#1a1400)',
 ARRAY['Mastercard','Afrique','Intégrale','Urgent'], true, 5670, 342,
 'https://mastercardfdn.org/scholars'),

('aga-khan-developpement-2025',
 'Bourse Aga Khan pour le Développement International',
 'Aga Khan Foundation', 'International', '🌍', 'Master', 'Économie',
 '2025-03-15', true, 'Intégrale avec prêt partiellement remboursable',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Aga Khan','Développement','Master'], true, 2890, 198,
 'https://www.akdn.org/our-agencies/aga-khan-foundation'),

('doctorat-allemagne-daad-2025',
 'Bourse DAAD — Doctorat en Allemagne pour candidats africains',
 'DAAD', 'Allemagne', '🇩🇪', 'Doctorat', 'Sciences',
 '2025-05-31', false, '1 200 €/mois + assurance maladie + allocation logement',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['DAAD','Allemagne','Doctorat','Sciences'], true, 1980, 134,
 'https://www.daad.de/en/'),

('commonwealth-master-2025',
 'Commonwealth Scholarships — Masters au Royaume-Uni',
 'Commission des Bourses du Commonwealth', 'Royaume-Uni', '🇬🇧', 'Master', 'Toutes disciplines',
 '2025-02-28', true, '100% frais de scolarité + 1 236 £/mois',
 'linear-gradient(135deg,#001018,#001a28)',
 ARRAY['Commonwealth','UK','Master','Urgent'], true, 4120, 267,
 'https://cscuk.fcdo.gov.uk/scholarships/'),

('inria-phd-afrique-numerique',
 'Bourses INRIA — Doctorat en Intelligence Artificielle pour l''Afrique',
 'INRIA', 'France', '🇫🇷', 'Doctorat', 'Sciences',
 '2025-06-30', false, '2 100 €/mois net + couverture sociale',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['INRIA','France','IA','Doctorat'], true, 1560, 89,
 'https://www.inria.fr/fr/postuler-these'),

('banque-africaine-dev-postdoc',
 'Programme Postdoctoral de la Banque Africaine de Développement',
 'Banque Africaine de Développement', 'Côte d''Ivoire', '🇨🇮', 'Postdoc', 'Économie',
 '2025-04-30', false, '5 000 USD/mois + frais de recherche',
 'linear-gradient(135deg,#0a0800,#1a1400)',
 ARRAY['BAD','Postdoc','Économie'], true, 890, 67,
 'https://www.afdb.org'),

('fulbright-afrique-subsaharienne',
 'Bourse Fulbright — Masters et Doctorats aux USA pour Africains',
 'Département d''État américain', 'États-Unis', '🇺🇸', 'Master', 'Toutes disciplines',
 '2025-05-15', false, 'Intégrale : frais + J-1 + bourse mensuelle',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['Fulbright','USA','Master','Doctorat'], true, 3780, 234,
 'https://foreign.fulbrightonline.org'),

('erasmus-mundus-afrique-2025',
 'Erasmus Mundus Joint Master Degrees — Quota Afrique 2025',
 'Commission Européenne (Erasmus+)', 'Europe', '🌍', 'Master', 'Toutes disciplines',
 '2025-01-31', true, '1 400 €/mois + frais de scolarité 9 000 €/an',
 'linear-gradient(135deg,#001018,#001a28)',
 ARRAY['Erasmus','Europe','Master','Urgent'], true, 6230, 389,
 'https://www.eacea.ec.europa.eu/erasmus-plus'),

('uct-vice-chancellor-scholarships',
 'Vice-Chancellor''s Scholarships — Université du Cap',
 'Université du Cap (UCT)', 'Afrique du Sud', '🇿🇦', 'Master', 'Toutes disciplines',
 '2025-07-31', false, '80 000 ZAR/an + frais de scolarité',
 'linear-gradient(135deg,#0e0005,#1a000a)',
 ARRAY['UCT','Afrique du Sud','Master'], true, 1230, 78,
 'https://www.uct.ac.za/apply/funding'),

('african-leadership-mba-bourse',
 'Bourse African Leadership University — MBA Impact Africain',
 'African Leadership University (ALU)', 'Rwanda', '🇷🇼', 'Master', 'Économie',
 '2025-03-01', true, '50 à 100% des frais selon mérite',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['ALU','Rwanda','MBA','Leadership'], true, 2340, 156,
 'https://www.alueducation.com'),

('gates-cambridge-scholarship',
 'Gates Cambridge Scholarship — Ouvert aux ressortissants africains',
 'Fondation Bill & Melinda Gates', 'Royaume-Uni', '🇬🇧', 'Doctorat', 'Sciences',
 '2025-10-12', false, 'Intégrale : frais + 21 000 £/an minimum',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['Gates','Cambridge','Doctorat','Excellence'], true, 4560, 312,
 'https://www.gatescambridge.org'),

('kofi-annan-leadership-scholarship',
 'Kofi Annan Foundation — Bourse Leadership Africain',
 'Fondation Kofi Annan', 'International', '🌍', 'Master', 'Toutes disciplines',
 '2025-04-01', false, '25 000 USD pour Master en gouvernance',
 'linear-gradient(135deg,#0a0500,#1a0e00)',
 ARRAY['Kofi Annan','Leadership','Gouvernance'], true, 1890, 112,
 'https://kofiannanfoundation.org'),

('wbi-afrique-recherche-doctorat',
 'World Bank Institute — Bourses de Recherche Doctoral pour Africains',
 'Institut de la Banque Mondiale', 'International', '🌍', 'Doctorat', 'Économie',
 '2025-06-15', false, '2 500 USD/mois + budget recherche 10 000 USD',
 'linear-gradient(135deg,#0a0800,#1a1400)',
 ARRAY['Banque Mondiale','Doctorat','Recherche','Économie'], true, 2100, 143,
 'https://www.worldbank.org/en/programs/scholarships'),

('sciences-po-afrique-master',
 'Sciences Po Paris — Programme Afrique, 20 bourses intégrales',
 'Sciences Po Paris', 'France', '🇫🇷', 'Master', 'Toutes disciplines',
 '2025-03-20', false, 'Intégrale : frais 14 000 €/an + bourse 1 000 €/mois',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['Sciences Po','France','Master'], true, 3120, 198,
 'https://www.sciencespo.fr/admissions/fr/aide-financiere.html'),

('african-women-stem-fellowship',
 'African Women in STEM Fellowship — Doctorat et Postdoc',
 'African Academy of Sciences (AAS)', 'Kenya', '🇰🇪', 'Doctorat', 'Sciences',
 '2025-05-01', false, '3 000 USD/mois + équipements de laboratoire',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Femmes','STEM','Sciences','Doctorat'], true, 1670, 98,
 'https://www.aasciences.africa'),

('canada-afrique-bourse-excellence',
 'Gouvernement du Canada — Bourses pour Africains francophones',
 'Affaires Mondiales Canada', 'Canada', '🇨🇦', 'Master', 'Toutes disciplines',
 '2025-02-15', true, 'Intégrale + billet aller-retour + assurance',
 'linear-gradient(135deg,#001018,#001a28)',
 ARRAY['Canada','Francophone','Master','Urgent'], true, 4780, 287,
 'https://www.affairesmondialescanada.ca/bourses'),

('university-tokyo-jica-scholarship',
 'JICA — Bourse Université de Tokyo pour doctorants africains',
 'Japan International Cooperation Agency (JICA)', 'Japon', '🇯🇵', 'Doctorat', 'Sciences',
 '2025-07-01', false, '143 000 ¥/mois + frais de scolarité',
 'linear-gradient(135deg,#0e0005,#1a000a)',
 ARRAY['Japon','JICA','Doctorat'], true, 1340, 89,
 'https://www.jica.go.jp/english/programs/scholarship/'),

('soros-open-society-afrique',
 'Open Society Foundations — Bourses pour défenseurs des droits',
 'Open Society Foundations', 'International', '🌍', 'Master', 'Toutes disciplines',
 '2025-04-20', false, '30 000 USD pour Master en droit et gouvernance',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['Open Society','Droits','Gouvernance','Droit'], true, 2230, 134,
 'https://www.opensocietyfoundations.org/grants'),

('au-scholarship-technical-excellence',
 'Union Africaine — Bourses d''Excellence Technique et Scientifique',
 'Commission de l''Union Africaine', 'Éthiopie', '🇪🇹', 'Licence', 'Sciences',
 '2025-08-31', false, '500 USD/mois + frais de scolarité dans universités partenaires',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Union Africaine','Excellence','Sciences','Licence'], true, 1120, 67,
 'https://au.int/scholarships');

-- ============================================================
-- OPPORTUNITÉS (20)
-- ============================================================
INSERT INTO public.opportunities
  (slug, title, company, company_initials, location, country, flag, type, sector,
   description, skills, deadline, salary, remote, featured, published, image_gradient)
VALUES

('google-africa-swe-lagos-2025',
 'Software Engineer — Google for Africa Program',
 'Google Africa', 'GA', 'Lagos, Nigeria', 'Nigeria', '🇳🇬', 'Emploi CDI', 'Tech',
 'Rejoignez l''équipe Google Africa et contribuez à des produits qui servent des millions d''Africains, en relevant des défis techniques liés aux contraintes de connectivité du marché africain.',
 ARRAY['Python','Go','Distributed Systems','Machine Learning','API Design'],
 '2025-03-31', '85 000 - 120 000 USD/an + actions', false, true, true,
 'linear-gradient(135deg,#001a0f,#002e1a)'),

('banque-mondiale-consultant-abidjan',
 'Consultant Senior en Développement Économique',
 'Banque Mondiale', 'BM', 'Abidjan, Côte d''Ivoire', 'Côte d''Ivoire', '🇨🇮', 'Emploi CDI', 'Finance',
 'La Banque Mondiale recrute un consultant senior pour accompagner les gouvernements d''Afrique de l''Ouest dans leurs réformes économiques et leurs stratégies de développement durable.',
 ARRAY['Économie du développement','Analyse de politiques','Excel avancé','Rédaction FR/EN'],
 '2025-04-15', '8 000 - 12 000 USD/mois', false, false, true,
 'linear-gradient(135deg,#0a0800,#1a1400)'),

('safaricom-product-manager-nairobi',
 'Product Manager — Innovation Fintech M-Pesa',
 'Safaricom', 'SC', 'Nairobi, Kenya', 'Kenya', '🇰🇪', 'Emploi CDI', 'Fintech',
 'Safaricom, opérateur de M-Pesa et leader de l''innovation fintech africaine, recherche un Product Manager expérimenté pour développer la prochaine génération de services financiers digitaux.',
 ARRAY['Product Management','Agile','User Research','Data Analysis','Fintech'],
 '2025-03-15', '4 500 - 6 000 USD/mois + bonus', false, true, true,
 'linear-gradient(135deg,#001a0f,#002e1a)'),

('onu-addis-stage-politique',
 'Stage — Analyste Politiques Publiques, Bureau Afrique ONU',
 'Nations Unies (UNECA)', 'ONU', 'Addis-Abeba, Éthiopie', 'Éthiopie', '🇪🇹', 'Stage', 'Institutions internationales',
 'L''UNECA offre un stage de 6 mois au sein de son département des politiques macroéconomiques, idéal pour les étudiants en économie et sciences politiques.',
 ARRAY['Recherche','Rédaction de rapports','Analyse de données','Statistiques'],
 '2025-02-28', 'Non rémunéré (per diem)', false, false, true,
 'linear-gradient(135deg,#050010,#0a0020)'),

('orange-digital-center-dakar',
 'Développeur Full Stack — Orange Digital Center Dakar',
 'Orange Sénégal', 'OS', 'Dakar, Sénégal', 'Sénégal', '🇸🇳', 'Emploi CDI', 'Tech',
 'L''Orange Digital Center recrute des développeurs pour son incubateur de startups africaines. Vous accompagnerez des entrepreneurs dans le développement de leurs produits numériques.',
 ARRAY['React','Node.js','PostgreSQL','Docker','Git'],
 '2025-03-30', '700 000 - 950 000 FCFA/mois', false, false, true,
 'linear-gradient(135deg,#001a0f,#002e1a)'),

('african-development-bank-economist',
 'Économiste — Département Intégration Régionale BAD',
 'Banque Africaine de Développement', 'BAD', 'Abidjan, Côte d''Ivoire', 'Côte d''Ivoire', '🇨🇮', 'Emploi CDI', 'Finance',
 'La BAD recrute un économiste pour analyser les dynamiques commerciales intra-africaines et produire des recommandations de politique économique dans le cadre de la ZLECAf.',
 ARRAY['Économétrie','R/Stata','Commerce international','Économie africaine'],
 '2025-05-31', '6 500 - 9 000 USD/mois exempt d''impôt', false, false, true,
 'linear-gradient(135deg,#0a0800,#1a1400)'),

('jumia-data-scientist-remote',
 'Data Scientist Senior — E-commerce & Logistique Jumia',
 'Jumia Technologies', 'JT', 'Télétravail (Afrique)', 'Nigeria', '🇳🇬', 'Emploi CDI', 'Tech',
 'Jumia cherche un data scientist pour optimiser ses algorithmes de recommandation et ses modèles de prévision logistique à l''échelle de 11 pays africains.',
 ARRAY['Python','TensorFlow','SQL','Spark','Tableau'],
 '2025-04-01', '45 000 - 65 000 USD/an', true, true, true,
 'linear-gradient(135deg,#001a0f,#002e1a)'),

('mtn-group-marketing-johannesburg',
 'Head of Digital Marketing — MTN Group',
 'MTN Group', 'MTN', 'Johannesburg, Afrique du Sud', 'Afrique du Sud', '🇿🇦', 'Emploi CDI', 'Télécommunications',
 'MTN Group, présent dans 19 pays africains, recherche son Head of Digital Marketing pour piloter la transformation numérique de sa stratégie à l''échelle continentale.',
 ARRAY['Marketing Digital','SEO/SEM','CRM','Analytics','Management'],
 '2025-03-20', '18 000 - 25 000 ZAR/mois + avantages', false, false, true,
 'linear-gradient(135deg,#0e0005,#1a000a)'),

('attijariwafa-stage-fintech-casablanca',
 'Stage Fintech — Analyse Risques & Innovation Digitale',
 'Attijariwafa Bank', 'AWB', 'Casablanca, Maroc', 'Maroc', '🇲🇦', 'Stage', 'Banque',
 'Attijariwafa Bank propose un stage de 6 mois au sein de sa Direction de l''Innovation Digitale sur les projets fintech, blockchain et paiements mobiles.',
 ARRAY['Finance','Analyse de risques','Excel','SQL','PowerPoint'],
 '2025-02-20', '4 500 MAD/mois', false, false, true,
 'linear-gradient(135deg,#0a0800,#1a1400)'),

('who-epidemiologiste-afro',
 'Épidémiologiste de terrain — OMS Bureau Afrique',
 'Organisation Mondiale de la Santé', 'OMS', 'Brazzaville, Congo', 'Congo', '🇨🇬', 'Emploi CDI', 'Santé',
 'L''OMS Africa recherche un épidémiologiste pour renforcer les capacités de surveillance dans 10 pays d''Afrique centrale.',
 ARRAY['Épidémiologie','SPSS/R','Surveillance épidémiologique','Urgences sanitaires'],
 '2025-04-30', 'Grade P4 ONU : 7 000 - 9 000 USD/mois', false, false, true,
 'linear-gradient(135deg,#001005,#001a0a)'),

('equity-bank-credit-analyst-kenya',
 'Credit Analyst Graduate — Financement des PME Africaines',
 'Equity Bank Kenya', 'EBK', 'Nairobi, Kenya', 'Kenya', '🇰🇪', 'Graduate', 'Banque',
 'Equity Bank recrute des jeunes diplômés dans son programme Graduate pour l''analyse crédit dédié aux PME et entrepreneurs africains.',
 ARRAY['Finance','Analyse financière','Excel','Crédit','Business Development'],
 '2025-03-10', '85 000 - 120 000 KES/mois', false, false, true,
 'linear-gradient(135deg,#0a0800,#1a1400)'),

('unicef-communication-abuja',
 'Chargé de Communication & Plaidoyer — UNICEF Nigeria',
 'UNICEF Nigéria', 'UN', 'Abuja, Nigeria', 'Nigeria', '🇳🇬', 'Emploi CDI', 'ONG',
 'L''UNICEF Nigeria recrute un chargé de communication pour sa campagne de vaccination et d''éducation touchant 20 millions d''enfants.',
 ARRAY['Communication','Rédaction','Réseaux sociaux','Plaidoyer','Anglais'],
 '2025-05-15', 'Grade NO-B : 4 500 - 6 000 USD/mois', false, false, true,
 'linear-gradient(135deg,#050010,#0a0020)'),

('free-senegal-ingenieur-reseau-5g',
 'Ingénieur Réseau Senior — Déploiement 5G Afrique de l''Ouest',
 'Free Sénégal', 'FS', 'Dakar, Sénégal', 'Sénégal', '🇸🇳', 'Emploi CDI', 'Télécommunications',
 'Free Sénégal accelere son déploiement 5G en Afrique de l''Ouest et recherche des ingénieurs réseaux pour piloter des projets d''infrastructure dans 4 pays.',
 ARRAY['5G','Réseaux mobiles','CISCO','RAN','Télécommunications'],
 '2025-04-15', '600 000 - 900 000 FCFA/mois', false, false, true,
 'linear-gradient(135deg,#001018,#001a28)'),

('techstars-africa-program-manager',
 'Program Manager — Techstars Africa Accelerator',
 'Techstars Africa', 'TA', 'Nairobi, Kenya (Hybride)', 'Kenya', '🇰🇪', 'Emploi CDI', 'Startup',
 'Techstars Africa recherche un Program Manager passionné pour gérer les 10 startups de la nouvelle cohorte et coordonner le réseau de mentors.',
 ARRAY['Gestion de programme','Écosystème startup','Mentoring','Networking'],
 '2025-03-25', '5 000 - 7 000 USD/mois', true, true, true,
 'linear-gradient(135deg,#001a0f,#002e1a)'),

('ifc-investissement-infrastructure-vert',
 'Analyste Investissement — Infrastructure Énergie Verte IFC',
 'International Finance Corporation (IFC)', 'IFC', 'Johannesburg, Afrique du Sud', 'Afrique du Sud', '🇿🇦', 'Emploi CDI', 'Finance',
 'L''IFC recrute un analyste pour évaluer et structurer des investissements dans les énergies renouvelables en Afrique subsaharienne.',
 ARRAY['Finance de projet','Modélisation financière','Énergie verte','Due diligence'],
 '2025-06-30', '8 000 - 12 000 USD/mois', false, false, true,
 'linear-gradient(135deg,#001018,#001a28)'),

('airtel-africa-hr-manager-rwanda',
 'Human Resources Manager — Afrique Francophone',
 'Airtel Africa', 'AA', 'Kigali, Rwanda', 'Rwanda', '🇷🇼', 'Emploi CDI', 'Ressources humaines',
 'Airtel Africa recherche un HR Manager pour superviser sa politique RH dans les pays francophones, couvrant 2 500 employés dans 6 pays.',
 ARRAY['RH','Droit du travail','SIRH','Management interculturel','Français/Anglais'],
 '2025-04-20', '4 000 - 5 500 USD/mois', false, false, true,
 'linear-gradient(135deg,#0e0005,#1a000a)'),

('msf-consultant-sante-terrain',
 'Consultant Santé Publique — Mission Terrain Afrique (Freelance)',
 'Médecins Sans Frontières', 'MSF', 'Terrain Afrique subsaharienne', 'International', '🌍', 'Freelance', 'Santé',
 'MSF recrute des consultants en santé publique pour des missions de 3 à 12 mois sur le terrain en Afrique subsaharienne. Profil médical ou para-médical requis.',
 ARRAY['Santé publique','Urgences humanitaires','Médecine tropicale','Adaptabilité'],
 '2025-12-31', '2 800 - 4 200 EUR/mois selon expérience', false, false, true,
 'linear-gradient(135deg,#001005,#001a0a)'),

('wfp-logistique-humanitaire-juba',
 'Officier Logistique Humanitaire — PAM Soudan du Sud',
 'Programme Alimentaire Mondial (PAM)', 'PAM', 'Juba, Soudan du Sud', 'Soudan du Sud', '🌍', 'Emploi CDI', 'Humanitaire',
 'Le PAM recrute un officier logistique pour coordonner la chaîne humanitaire dans un contexte complexe, gérant 120 000 tonnes de denrées par an.',
 ARRAY['Logistique humanitaire','Supply chain','Gestion de crise','Anglais'],
 '2025-03-31', 'Grade P3 ONU : 5 500 - 7 500 USD/mois', false, false, true,
 'linear-gradient(135deg,#001018,#001a28)'),

('greenharvest-cto-cofondateur-accra',
 'Co-fondateur & CTO — Startup Agritech (Equity + Salaire)',
 'GreenHarvest Africa', 'GH', 'Accra, Ghana (Hybride)', 'Ghana', '🇬🇭', 'Emploi CDI', 'Agritech',
 'GreenHarvest Africa, startup en phase seed, cherche son co-fondateur technique pour développer une plateforme SaaS d''optimisation des rendements pour 50 000 exploitants.',
 ARRAY['Architecture logicielle','React Native','Python','IoT','Leadership technique'],
 '2025-02-28', '2 000 USD/mois + 8% equity', false, true, true,
 'linear-gradient(135deg,#001a0f,#002e1a)'),

('peacecorps-volontaire-enseignement-mada',
 'Volontaire International — Enseignement Sciences et Maths',
 'Peace Corps', 'PC', 'Antananarivo, Madagascar', 'Madagascar', '🇲🇬', 'Volontariat', 'Éducation',
 'Le Peace Corps recherche des volontaires pour enseigner les mathématiques et les sciences dans les lycées malgaches pendant 2 ans.',
 ARRAY['Enseignement','Maths','Sciences','Adaptabilité','Français'],
 '2025-07-31', 'Indemnité de subsistance + logement + couverture médicale', false, false, true,
 'linear-gradient(135deg,#0a0500,#1a0e00)');

-- ============================================================
-- ÉVÉNEMENTS (20)
-- ============================================================
INSERT INTO public.events
  (slug, title, type, location, country, flag, day, month, year, event_date,
   excerpt, organizer, attendees, event_url, image_gradient, tags, featured, published, views, saves_count)
VALUES

('africa-fintech-summit-nairobi-2025',
 'Africa Fintech Summit 2025 — Nairobi',
 'Conférence', 'Nairobi, Kenya', 'Kenya', '🇰🇪', '15', 'Mars', '2025', '2025-03-15',
 'Le plus grand événement fintech d''Afrique réunit 5 000 professionnels de la finance digitale, des régulateurs et des investisseurs pour deux jours d''innovations et de networking.',
 'Kenya Bankers Association & Strathmore University', '5 000 attendus',
 'https://africafintechsummit.com',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Fintech','Finance','Kenya','Networking'], true, true, 4230, 287),

('forum-economique-dakar-2025',
 'Forum Économique de Dakar — Investissements & Développement',
 'Forum', 'Dakar, Sénégal', 'Sénégal', '🇸🇳', '22', 'Avril', '2025', '2025-04-22',
 'Le Forum Économique de Dakar rassemble chefs d''entreprise, ministres et entrepreneurs pour débattre des priorités d''investissement en Afrique de l''Ouest.',
 'Gouvernement du Sénégal & CNCAS', '3 000 attendus',
 'https://forumeconomiquedakar.sn',
 'linear-gradient(135deg,#0a0800,#1a1400)',
 ARRAY['Économie','Investissement','Sénégal'], true, true, 2890, 178),

('african-tech-week-kigali-2025',
 'African Tech Week — Kigali 2025',
 'Conférence', 'Kigali, Rwanda', 'Rwanda', '🇷🇼', '8', 'Mai', '2025', '2025-05-08',
 'La semaine technologique africaine célèbre l''innovation numérique avec 200 speakers, 50 startups en showcase et 10 000 participants de 45 pays.',
 'Rwanda ICT Chamber & RDB', '10 000 attendus',
 'https://africantechweek.rw',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Tech','Innovation','Rwanda','Startups'], true, true, 6780, 412),

('cairo-international-book-fair-2025',
 'Foire Internationale du Livre du Caire — 57ème édition',
 'Salon', 'Le Caire, Égypte', 'Égypte', '🇪🇬', '23', 'Janvier', '2025', '2025-01-23',
 'La plus grande foire du livre du monde arabe et africain accueille 1 500 maisons d''édition de 54 pays pour 11 jours de culture autour du thème : ''L''Afrique lit''.',
 'Autorité Générale des Affaires Culturelles (Égypte)', '3 millions de visiteurs',
 'https://cairobookfair.org',
 'linear-gradient(135deg,#0a0500,#1a0e00)',
 ARRAY['Culture','Livres','Égypte','Littérature'], false, true, 12400, 567),

('hackathon-africa-climate-tech-2025',
 'Africa Climate Tech Hackathon — 72h pour sauver le continent',
 'Hackathon', 'Accra, Ghana + Distanciel', 'Ghana', '🇬🇭', '14', 'Juin', '2025', '2025-06-14',
 '500 développeurs et experts climatiques de 30 pays ont 72 heures pour créer des solutions aux défis climatiques. Prix total : 200 000 USD.',
 'GreenTech Africa & African Development Bank', '500 participants',
 'https://africaclimatetech.org',
 'linear-gradient(135deg,#001018,#001a28)',
 ARRAY['Hackathon','Climat','Tech','Ghana'], true, true, 3450, 234),

('sommet-sante-africaine-abidjan-2025',
 'Sommet Africain de la Santé — Couverture Universelle',
 'Sommet', 'Abidjan, Côte d''Ivoire', 'Côte d''Ivoire', '🇨🇮', '18', 'Septembre', '2025', '2025-09-18',
 'Les ministres de la santé des 54 États membres de l''UA se réunissent pour accélérer la mise en place de la couverture santé universelle.',
 'Union Africaine & OMS Bureau Afrique', '2 500 participants',
 'https://africanhealthsummit.org',
 'linear-gradient(135deg,#001005,#001a0a)',
 ARRAY['Santé','Couverture universelle','UA'], false, true, 1890, 123),

('lagos-fashion-week-2025',
 'Lagos Fashion Week 2025 — L''Afrique à la Mode',
 'Salon', 'Lagos, Nigeria', 'Nigeria', '🇳🇬', '27', 'Octobre', '2025', '2025-10-27',
 'La semaine de la mode de Lagos présente les collections de 60 créateurs africains et réunit acheteurs internationaux, presse et influenceurs.',
 'Lagos Fashion Week Ltd', '15 000 visiteurs',
 'https://lagosfashionweek.com',
 'linear-gradient(135deg,#0e0005,#1a000a)',
 ARRAY['Mode','Afrique','Culture','Nigeria'], false, true, 5670, 345),

('africa-education-forum-addis-2025',
 'Africa Education Forum — L''école africaine du 21ème siècle',
 'Forum', 'Addis-Abeba, Éthiopie', 'Éthiopie', '🇪🇹', '5', 'Juillet', '2025', '2025-07-05',
 'Forum continental sur la réforme des systèmes éducatifs réunissant ministres, pédagogues innovants et partenaires pour repenser l''école africaine.',
 'UNESCO & Union Africaine', '4 000 participants',
 'https://africaeducationforum.org',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['Éducation','Réforme','Éthiopie'], false, true, 2340, 167),

('joburg-international-jazz-festival-2025',
 'Johannesburg International Jazz Festival 2025',
 'Conférence', 'Johannesburg, Afrique du Sud', 'Afrique du Sud', '🇿🇦', '28', 'Mars', '2025', '2025-03-28',
 'Le plus grand festival de jazz d''Afrique australe célèbre sa 25ème édition avec 80 artistes sur 5 scènes pendant 3 jours de musique live.',
 'Metro FM & City of Johannesburg', '40 000 festivaliers',
 'https://joburgfestival.co.za',
 'linear-gradient(135deg,#0a0500,#1a0e00)',
 ARRAY['Jazz','Musique','Afrique du Sud','Festival'], false, true, 7890, 456),

('african-women-leadership-forum-2025',
 'African Women in Leadership Forum — Briser les Plafonds',
 'Forum', 'Nairobi, Kenya', 'Kenya', '🇰🇪', '12', 'Mars', '2025', '2025-03-12',
 'Le forum des femmes leaders africaines réunit 1 200 dirigeantes pour partager des stratégies de leadership, de mentorat et d''influence.',
 'African Women in Business Network', '1 200 participantes',
 'https://africanwomenleadership.org',
 'linear-gradient(135deg,#0e0005,#1a000a)',
 ARRAY['Femmes','Leadership','Empowerment','Kenya'], true, true, 3120, 234),

('smart-cities-africa-casablanca-2025',
 'Smart Cities Africa Summit 2025 — Casablanca',
 'Sommet', 'Casablanca, Maroc', 'Maroc', '🇲🇦', '10', 'Juin', '2025', '2025-06-10',
 'Le sommet réunit urbanistes, maires africains et startups pour explorer les solutions de villes intelligentes adaptées aux réalités africaines.',
 'Ville de Casablanca & ONU-Habitat', '3 500 participants',
 'https://smartcitiesafrica.ma',
 'linear-gradient(135deg,#050010,#0a0020)',
 ARRAY['Villes','Smart City','Urbanisme','Maroc'], false, true, 1780, 98),

('pan-african-business-summit-abuja-2025',
 'Pan-African Business Summit — Abuja 2025',
 'Sommet', 'Abuja, Nigeria', 'Nigeria', '🇳🇬', '20', 'Mai', '2025', '2025-05-20',
 'Le sommet continental réunit 500 CEO africains et 200 investisseurs pour accélérer les investissements inter-africains dans le cadre de la ZLECAf.',
 'Nigeria Investment Promotion Commission', '700 participants',
 'https://panafricanbusiness.ng',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Business','Investissement','Nigeria','ZLECAf'], true, true, 2560, 178),

('afrotech-hackathon-douala-2025',
 'AfroTech Hackathon — Solutions pour l''Afrique Francophone',
 'Hackathon', 'Douala, Cameroun', 'Cameroun', '🇨🇲', '25', 'Avril', '2025', '2025-04-25',
 '300 développeurs francophones ont 48h pour coder des solutions en santé, agriculture et éducation. Prix : 50 000 USD + accompagnement incubateur.',
 'Orange Cameroun & StartupCameroun', '300 participants',
 'https://afroteckhackathon.cm',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Hackathon','Cameroun','Francophone'], false, true, 1890, 134),

('cape-town-international-film-festival-2025',
 'Festival International du Film du Cap 2025',
 'Conférence', 'Le Cap, Afrique du Sud', 'Afrique du Sud', '🇿🇦', '15', 'Novembre', '2025', '2025-11-15',
 'Le plus important festival de cinéma africain présente 200 films de 45 pays pendant 12 jours avec sélection compétitive et marché du film.',
 'DIFF Foundation & NFF', '80 000 spectateurs',
 'https://www.diff.co.za',
 'linear-gradient(135deg,#0a0500,#1a0e00)',
 ARRAY['Cinéma','Film','Afrique du Sud','Festival'], false, true, 4560, 278),

('africa-renewable-energy-summit-2025',
 'Africa Renewable Energy Summit — Vers 100% Énergies Propres',
 'Sommet', 'Nairobi, Kenya', 'Kenya', '🇰🇪', '2', 'Octobre', '2025', '2025-10-02',
 'Le sommet continental rassemble gouvernements, investisseurs et industriels pour accélérer la transition vers 100% d''énergies renouvelables en Afrique d''ici 2050.',
 'IRENA Africa & Kenya Power', '2 000 participants',
 'https://africaenergyweek.com',
 'linear-gradient(135deg,#001018,#001a28)',
 ARRAY['Énergie','Renouvelable','Kenya'], false, true, 2340, 156),

('dakar-architecture-biennale-2025',
 'Biennale d''Architecture de Dakar — Formes Africaines',
 'Salon', 'Dakar, Sénégal', 'Sénégal', '🇸🇳', '14', 'Février', '2025', '2025-02-14',
 'La biennale explore l''identité architecturale africaine contemporaine avec les œuvres de 80 architectes et une réflexion sur l''urbanisme durable tropical.',
 'Ordre des Architectes du Sénégal', '25 000 visiteurs',
 'https://biennalearchitecturedakar.sn',
 'linear-gradient(135deg,#0a0500,#1a0e00)',
 ARRAY['Architecture','Design','Sénégal','Urbanisme'], false, true, 1230, 89),

('africa-agribusiness-summit-accra-2025',
 'Africa Agribusiness & Food Summit — Nourrir le Continent',
 'Forum', 'Accra, Ghana', 'Ghana', '🇬🇭', '8', 'Septembre', '2025', '2025-09-08',
 'Le forum agrobusiness réunit transformateurs alimentaires, agriculteurs innovants et investisseurs pour accélérer la transformation agricole africaine.',
 'AGRA & Gouvernement du Ghana', '4 500 participants',
 'https://africaagribusiness.org',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Agriculture','Agribusiness','Ghana'], true, true, 1890, 123),

('digital-africa-summit-tunis-2025',
 'Digital Africa Summit 2025 — Tunis',
 'Sommet', 'Tunis, Tunisie', 'Tunisie', '🇹🇳', '3', 'Décembre', '2025', '2025-12-03',
 'Le sommet analyse les mutations numériques du continent avec un focus sur l''IA, la cybersécurité et le commerce électronique transfrontalier africain.',
 'Ministère des Technologies tunisien & Smart Africa', '3 000 participants',
 'https://digitalafrica.tn',
 'linear-gradient(135deg,#001018,#001a28)',
 ARRAY['Digital','Numérique','Tunisie','IA'], false, true, 1560, 98),

('francophonie-culture-summit-montreal-2025',
 'Sommet Culturel de la Francophonie — Voix Africaines',
 'Sommet', 'Montréal, Canada', 'Canada', '🇨🇦', '16', 'Octobre', '2025', '2025-10-16',
 'Le sommet donne la parole aux créateurs africains francophones : littérature, cinéma, musique, arts plastiques. 150 artistes africains présents.',
 'Organisation Internationale de la Francophonie', '50 000 visiteurs',
 'https://sommetculturelfrancophonie.org',
 'linear-gradient(135deg,#0a0500,#1a0e00)',
 ARRAY['Francophonie','Culture','Canada','Arts'], false, true, 2340, 145),

('startup-africa-challenge-finals-2025',
 'Startup Africa Challenge 2025 — Grande Finale Kigali',
 'Conférence', 'Kigali, Rwanda', 'Rwanda', '🇷🇼', '20', 'Novembre', '2025', '2025-11-20',
 'La grande finale du plus important concours de startups africaines réunit 20 finalistes de 54 pays pour pitcher devant 100 investisseurs. Prix : 1 million USD.',
 'African Development Bank & Tony Elumelu Foundation', '2 000 participants',
 'https://startupafrica.org',
 'linear-gradient(135deg,#001a0f,#002e1a)',
 ARRAY['Startups','Entrepreneuriat','Rwanda','Investissement'], true, true, 5670, 389),

('zanzibar-international-film-festival-2025',
 'Festival International du Film de Zanzibar — Dhow Countries',
 'Conférence', 'Zanzibar, Tanzanie', 'Tanzanie', '🇹🇿', '7', 'Juillet', '2025', '2025-07-07',
 'Le ZIFF célèbre sa 28ème édition présentant les cinématographies africaines, arabes et de l''Océan Indien dans les lieux patrimoniaux de Stone Town.',
 'ZIFF Foundation', '30 000 spectateurs',
 'https://ziff.or.tz',
 'linear-gradient(135deg,#001018,#001a28)',
 ARRAY['Cinéma','Tanzanie','Culture','Festival'], false, true, 2890, 178);

-- ── Confirmation ─────────────────────────────────────────────
DO $$
DECLARE
  cnt_a INT; cnt_b INT; cnt_o INT; cnt_e INT;
BEGIN
  SELECT COUNT(*) INTO cnt_a FROM public.articles;
  SELECT COUNT(*) INTO cnt_b FROM public.scholarships;
  SELECT COUNT(*) INTO cnt_o FROM public.opportunities;
  SELECT COUNT(*) INTO cnt_e FROM public.events;
  RAISE NOTICE '✅ Seed OK : % articles | % bourses | % opportunités | % événements',
    cnt_a, cnt_b, cnt_o, cnt_e;
END $$;